name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build static site
      run: |
        # Create static version for GitHub Pages
        echo "Building static version for GitHub Pages..."
        
        # Backup original index.html
        cp index.html index-original.html
        
        # Use the GitHub Pages version as the main index
        cp github-pages.html index.html
        
        echo "GitHub Pages version is now the main index.html"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
